name: stackdriver_dart
description: Flutter package for reporting uncaught application errors and HTTP failures to Google Cloud Error Reporting.
version: 2.0.1
homepage: https://playon.jp
repository: https://github.com/ueki-tomohiro/stackdriver_dart

environment:
  sdk: ^3.11.1
  flutter: ">=3.41.4"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  pretty_http_logger: ^1.0.5
  dio: ^5.9.2
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
