name: stackdriver_dart
description: logging stackdriver report
version: 1.0.9
homepage: https://playon.jp
repository: https://github.com/ueki-tomohiro/stackdriver_dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  http_extensions: ^1.0.0
  dio: ^5.3.2
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
