name: stackdriver_dart
description: stackdriver dart
version: 1.0.3
homepage: http://playon.jp
repository: https://github.com/ueki-tomohiro/stackdriver_dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  http_extensions: ^1.0.0
  dio: ^4.0.3
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
